name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created] 
  workflow_dispatch:  

jobs:
  build_docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          push: false
          load: true  # 这会将镜像加载到 Docker 守护进程中
          tags: |
            qwen2api:latest
            qwen2api:${{ github.sha }}

      - name: 提取 Docker 镜像
        run: docker save qwen2api:latest > image.tar

      - name: 上传 Docker 镜像
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
